####################
DATABASE:
  AUTH:
    HOST: "127.0.0.1"
    PORT: 27017
  NAME: "Bunkers"
  COLLECTIONS:
    INFORMATION: "Information"
    TEAMS: "Teams"
    PROFILES: "Profiles"
####################